[package]
name = "file-organizer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
log = "0.4"
simple_logger = "5.0.0"
glob = "0.3"
walkdir = "2.5"
crc = "3.2"
